version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: fraudlens-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vibhoo@83139
      MYSQL_DATABASE: fraudlens
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pvibbhoo@83139"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:7
    container_name: fraudlens-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: fraudlens

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fraudlens-backend
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: vibhoo@83139
      MYSQL_DB: fraudlens
      MONGO_URI: mongodb://mongodb:27017/fraudlens
      AI_ENGINE_URL: http://ai-engine:8000
      JWT_SECRET: fraudlens_jwt_secret_2024_xK9mP3qR
      JWT_EXPIRES_IN: 7d
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_started
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads_data:/app/uploads

  ai-engine:
    build:
      context: ./ai-engine
      dockerfile: Dockerfile
    container_name: fraudlens-ai-engine
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/fraudlens
      FAISS_STORE_PATH: /app/faiss_indexes
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    depends_on:
      - mongodb
    volumes:
      - ./ai-engine:/app
      - faiss_data:/app/faiss_indexes

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fraudlens-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
  mongo_data:
  uploads_data:
  faiss_data:
